before:
  hooks:
    - go mod tidy
builds:
  - skip: true
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
  sort: asc
  use: github