name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
        #path: ./src/github.com/${{ github.repository }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

#    - name: Get dependencies
#      run: |
#        go get -v -t -d ./...
#        if [ -f Gopkg.toml ]; then
#            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#            dep ensure
#        fi

    - name: Build Client
      run: go build client/
    
    - name: Build Enum
      run: go build enum/

    - name: Build model
      run: go build model/

    - name: Test
      run: go test -v ./integration/...
